### ISSUE TITLE
Passing additional arguments to fusermount

### ISSUE THREAD

**Issue by gchiesa** [bwester/consulfs#2]
Hi,
how can I pass additional fusermount options using consulfs binary? 
It supports only -debug flag, correct?

**Comment by bwester** [comment]
I don't have any way to do that yet, but it seems useful!  What are you trying to achieve?

**Comment by gchiesa78** [comment]
I would like to use at least the options like uid, gid, and allow_others when mounting the consulfs.

**Comment by bwester** [comment]
I've added support for those mount options in commit 60e037c7. Let me know how those work for you.

**Comment by gchiesa** [comment]
I just tried and it works perfectly. 
Thank you for your prompt feedback.
