### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by bhourigan** [bwester/consulfs#3]
Following the install instructions and running `go get github.com/bwester/consulfs/bin/consulfs` returns the following error:

```
server$ go get github.com/bwester/consulfs/bin/consulfs
# github.com/bwester/consulfs/Godeps/_workspace/src/bazil.org/fuse
/root/gocode/src/github.com/bwester/consulfs/Godeps/_workspace/src/bazil.org/fuse/fuse.go:422:20: error: reference to undefined identifier ‘sync.Pool’
 var reqPool = sync.Pool{
                    ^
/root/gocode/src/github.com/bwester/consulfs/Godeps/_workspace/src/bazil.org/fuse/fuse.go:422:24: error: expected ‘;’ or newline after top level declaration
 var reqPool = sync.Pool{
                        ^
```

**Comment by bwester** [comment]
@bhourigan, what version of Golang are you using?

**Comment by bwester** [comment]
@bhourigan, I suspect that your version of Golang is too old. `sync.Pool` should be a valid identifier in Golang 1.3 or later. It is being used in an important dependency ([bazil.org/fuse](https://bazil.org/fuse/)). Short of maintaining my own fork of that package (which has too many drawbacks), this isn't something I can change.

**Comment by bhourigan** [comment]
@bwester you're right - I had figured this out already, but forgot to close the issue. thank you!
