### ISSUE TITLE
Mount subpath in consul

### ISSUE THREAD

**Issue by Alars-ALIT** [bwester/consulfs#5]
A nice feature would be to be able to mount a subpath in consul. We use consul for many roles, and file storage is just one of them. It seems unnecessary to expose the whole K/V store for all clients.

**Comment by bwester** [comment]
That does seem very useful. Thanks for the suggestion!

**Comment by bwester** [comment]
I just pushed a new `-root` option for `consulfs` that will allow you to specify the Consul subpath that you want to mount as the filesystem root. Please re-open this ticket if you find any bugs.
